# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c36684967367e9d773d3cfa126012d3fdf6cdfd4b5d4802cd8e73f6be76f0c440ba51f439c1956e50afff82b156092a98f1b806afc329aec4055a59e9bfc4d4

test:
  secret_key_base: b2bdac2e8e53a6a571839f7ea8b79fe6f8e43fead05406ec7237006022cbf234cf5d03237077f3ad0a8b1d85329c22d64b42eda4bc2865b0824b736fe0aa4c80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
